config/routes.rb
Kakaoreview::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :main, :only => ['index']
  resources :quotes do
    resources :comments
    member do
      post :rate
    end
  end
  resources :chats do
    resources :parts
    resources :messages
  end
	resources :emails

  match 'help' => 'main#help'

  root :to => 'main#index'

end

app/models/quote.rb
class Quote
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  include Mongoid::Paperclip

  #=== Fields
  field :title, type: String
  field :content, type: String
  field :img_file_name, type: String
  field :img_content_type, type: String
  field :img_file_size, type: Integer
  field :img_updated_at, type: DateTime

  
  attr_accessible :title, :content

  has_mongoid_attached_file :img



  has_many :comments
  belongs_to :chat
  belongs_to :user
  embeds_many :rate
end

app/controllers/quotes_controller.rb
#encoding: utf-8
class QuotesController < ApplicationController
  layout 'frame'

  def index
    sort = params[:sort]

    @quotes = Quote.all
  end

  def show
    @quote = Quote.find(params[:id])
    @comment = Comment.new
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  #async action
  def rate
    @quote = Quote.find(params[:id])
    
    if @quote.rate.where(:user_id => current_user.id).length > 0
      @result = {:status => false, :message => '이미 평가하셨습니다.'}
      return
    end

    @rate = Rate.new(:like => params[:like])
    @rate.quote = @quote
    @rate.user = current_user

    if @rate.save
      @result = {:status => true}
    else
      @result = {:status => false, :message => '저장 과정에서 오류가 발생했습니다.'}
    end
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_sidebar.html.erb
<ul class="nav nav-list">
  <li><%= link_to 'Recent', quotes_path %></li>
  <li class="nav-header">RANK BY</li>
  <li><%= link_to 'Daily', quotes_path(:sort => 'daily') %></li>
  <li><%= link_to 'Weekly', quotes_path(:sort => 'weekly') %></li>
  <li><%= link_to 'Monthly', quotes_path(:sort => 'monthly') %></li>
  <li class="divider"></li>
</ul>

app/views/quotes/index.html.erb
<h2>Quotes with ranking</h2>

<div>
<% @quotes.each do |q| %>
  <div>
    <%= link_to q.title, quote_path(q) %>
  </div>
<% end %>
</div>

app/views/quotes/rate.js.erb
<% if @result[:status] %>
  $(".quote_like_<%= @quote.id %>").html("<%= @quote.rate.likes.length %>");
  $(".quote_dislike_<%= @quote.id %>").html("<%= @quote.rate.dislikes.length %>");

<% else %>
  alert('<%= @result[:message] %>');
<% end %>

app/views/quotes/show.html.erb
<h3><%= @quote.title %></h3>

<div>
  <%= image_tag(@quote.img.url) %>
</div>

<div>
  <h5>Content</h5>
  <p>
    <%= @quote.content %>
  </p>
  <%= link_to 'Like', rate_quote_path(:like => true), :method => :post, :remote => true %> <span class="quote_like_<%= @quote.id %>"><%= @quote.rate.likes.length %></span>
  <%= link_to 'Dislike', rate_quote_path(:like => false), :method => :post, :remote => true %> <span class="quote_dislike_<%= @quote.id %>"><%= @quote.rate.dislikes.length %></span>
  <%= link_to '공유하기', '#' %>
</div>

<div>
  <h5>Comments</h5>
  <div>
    <%= form_for(@comment, :url => quote_comments_path(@quote)) do |f| %>
      <%= f.text_field :content %>
      <%= f.submit '작성' %>
    <% end %>
  </div>
  <div>
  <% if @quote.comments.length > 0 %>
    <% @quote.comments.each do |c| %>
      <b><%= c.user.username %></b>
      <%= c.content %>
    <% end %>
  <% else %>
    코멘트가 없습니다
  <% end %>
  </div>
</div>


<%= link_to 'Back', quotes_path %>