config/routes.rb
Kakaoreview::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :main, :only => ['index']
  resources :quotes do
    resources :comments
    member do
      post :rate
    end
  end
  resources :chats do
    resources :parts
    resources :messages
  end
	resources :emails

  match 'help' => 'main#help'

  root :to => 'main#index'

end

app/models/chat.rb
#coding: utf-8

class Chat
  require 'uri'

  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  include Mongoid::Paperclip

  #=== Fields
  field :title, type: String
  field :chatfile_file_name, type: String
  field :chatfile_content_type, type: String
  field :chatfile_file_size, type: Integer
  field :chatfile_updated_at, type: DateTime
  field :chat_type, type: Integer

  field :parsed, type: Boolean, :default => false


  attr_accessible :title
  attr_accessible :chat_type
  attr_accessible :chatfile

  has_mongoid_attached_file :chatfile


  belongs_to :user, :inverse_of => :chats
  embeds_many :messages
  embeds_many :attachments

  #has_and_belongs_to_many :readers, :class_name => "User", :join_table => "users_readable_chats"
  accepts_nested_attributes_for :messages


  scope :uploaded, where(:chat_type => UPLOADED)
  scope :created, where(:chat_type => CREATED)



  ### CRUD
  def self.create_chat chat_params, user
    new_chat = Chat.new(chat_params)
    new_chat.user = user
    
    if new_chat.save
      if chat_params[:chatfile]
        new_chat.parse_file
      end
      return new_chat
    else
      return
    end
  end

  def get_file filename
    file = self.attachments.where(:att_file_name => filename)
    if file.length > 0
      return file.first.att.url
    else
      return filename
    end
  end


  ### Parse methods
  def parse_android(f)
    res = []
    parsed_date = ""
    f.each do |l|
      next if l == "\r\n"

      if l.index('년').nil?
        # 사용자가 여러줄의 메시지를 보냈을 때
        # TODO handling multiline message
        next
      end
      if l.index('년') && l.index('월') && l.index('일') && l.index(',').nil?
        # 날짜 시간 시스템 메시지 패스
        next
      end
      # split datetime and others
      s = l.index(',')
      next if s.nil?
      # TODO s.nil? is error
      datetime = l[0..s-1]
      info = l[s+2..-1]

      # parse datetime

      s = datetime.index('일')
      date = datetime[0..s]
      time = datetime[s+2..-1]

      changed = false
      unless parsed_date == date
        parsed_date = date
        changed = true
      end


      # split name and message
      
      s = info.index(':')
      # 메시지가 아닌 system message
      if s.nil?
        name = nil
        unless info.index("초대").nil?
          type = INVITATION
          message = info[0..-3]
        else
          type = LEAVE
          message = info[0..-3]
        end
      # 사용자가 보낸 메시지
      else
        type = MESSAGE
        name = info[0..s-2]
        message = info[s+2..-3]
      end
      #
      # merge infos
      hash = Hash.new
      hash.merge!(:message_type => type)
      hash.merge!(:message => message)
      hash.merge!(:content => message_type(message))
      hash.merge!(:name => name, :isMine => name == "회원님") unless name.nil?
      if changed
        hash.merge!(:message_date => parsed_date)
      end
      hash.merge!(:message_time => time) unless time.nil?

      m = Message.new(hash)
      res << m
    end
    res
  end

  def parse_ios(f)
    res = []
    f.each do |l|
      next if l == "\r\n"

      # set message type
      if l.match(/\d{4}년 \d{1,2}월 \d{1,2}일 .요일/)
        type = DATE
      elsif l.match(/\d{4}\. \d{1,2}\. \d{1,2}\. 오(후|전) \d{1,2}:\d{1,2}:/) && l.match(/초대/)
        # 초대 system message
        type = INVITATION
      elsif l.match(/\d{4}\. \d{1,2}\. \d{1,2}\. 오(후|전) \d{1,2}:\d{1,2}:/) && l.match(/퇴장/)
        # 퇴장 system message
        type = LEAVE
      elsif l.match(/\d{4}\. \d{1,2}\. \d{1,2}\. 오(후|전) \d{1,2}:\d{1,2},/)
        # 사용자가 메시지를 보냈을 때
        type = MESSAGE
      elsif !l.match(/\d{4}\. \d{1,2}\. \d{1,2}\. 오(후|전) \d{1,2}:\d{1,2}/)
        # 사용자가 여러줄의 메시지를 보냈을 때
        type = MULTILINEMESSAGE
      else
        type = UNKNOWN
      end

      #parse date and set changed
      #TODO date changed?
      cond = (type == UNKNOWN or type == MULTILINEMESSAGE)
      unless cond
        time = l.match(/오(후|전) \d{1,2}:\d{1,2}/).to_s
      end

      info = l.sub(/\d{4}\. \d{1,2}\. \d{1,2}\. 오(후|전) \d{1,2}:\d{1,2}(,|:) /,'')
      if cond
        res[-1][:message] << "<br>" << info[0..-2]
        next
      else
        s = info.index(':')
        if s.nil?
          message = info[0..-3]
        else
          name = info[0..s-2]
          message = info[s+2..-2]
        end
      end

      hash = Hash.new
      hash.merge!(:message_type => type)
      hash.merge!(:content => message_type(message), :message => parse_misc(message))
      hash.merge!(:name => name, :isMine => name == "회원님") unless name.nil?
      hash.merge!(:message_time => time) unless time.nil?
      res << Message.new(hash)
    end
    res
  end

  def message_type(message)
    if message.match(/[0-9a-zA-Z\-=_]*[[:punct:]]jpg/)
      IMAGE
    elsif message.match(/[0-9a-zA-Z\-=_]*[[:punct:]]m4a/)
      AUDIO
    elsif message.match(/[0-9a-zA-Z\-=_]*[[:punct:]]mp4/)
      VIDEO
    else
      TEXT
    end
  end

  def parse_file
    if self.parsed == false
      f = File.open(self.chatfile.path)
      f = f.drop(5)
      type = ANDROID
      if f.first.match(',')
        type = ANDROID
      else
        type = IOS
      end

      if type == ANDROID
        res = parse_android(f)
      else
        res = parse_ios(f)
      end
      self.messages << res
      self.parsed = true
      self.save
    end
    #self.messages
  end

  def parse_misc(message)
    parse_emoticons(parse_links(message))
  end

  def parse_links(message)
    links = URI.extract(message)

    links.each do |k|
        message.gsub!(k, "<a href ='#{k}'>#{k}</a>") 
    end
    message
  end

  def parse_emoticons(message)
    dict = Hash[ 
      "(미소)" => 1, "(윙크)" => 2, "(방긋)" => 3, "(반함)" => 4, "(눈물)" => 5,
      "(절규)" => 6, "(크크)" => 7, "(메롱)" => 8, "(잘자)" => 9, "(잘난척)" => 10,
      "(헤롱)" => 11, "(놀람)" => 12, "(아픔)" => 13, "(당황)" => 14, "(풍선껌)" => 15, 
      "(버럭)" => 16, "(부끄)" => 17, "(궁금)" => 18, "(흡족)" => 19, "(깜찍)" => 20,
      "(으으)" => 21, "(민망)" => 22, "(곤란)" => 23, "(잠)" => 24, "(행복)" => 25,
      "(안도)" => 26, "(우웩)" => 27, "(외계인)" => 28, "(외계인녀)" => 72, "(공포)" => 29,
      "(근심)" => 30, "(악마)" => 31, "(썩소)" => 32, "(쳇)" => 33, "(야호)" => 69, 
      "(좌절)" => 70, "(삐짐)" => 71, "(하트)" => 34, "(실연)" => 74, "(별)" => 75, 
      "(브이)" => 73, "(오케이)" => 35, "(최고)" => 36, "(최악)" => 37, "(그만)" => 38, 
      "(땀)" => 39, "(알약)" => 40, "(밥)" => 41, "(커피)" => 42, "(맥주)" => 43, 
      "(소주)" => 44, "(와인)" => 79, "(치킨)" => 78, "(축하)" => 45, "(음표)" => 46, 
      "(선물)" => 47, "(케익)" => 48, "(촛불)" => 49, "(컵케익a)" => 50, "(컵케익b)" => 51, 
      "(해)" => 52, "(구름)" => 53, "(비)" => 54, "(눈)" => 55, "(똥)" => 56, 
      "(근조)" => 57, "(딸기)" => 58, "(호박)" => 59, "(입술)" => 60, "(야옹)" => 61, 
      "(돈)" => 62, "(담배)" => 63, "(축구)" => 64, "(야구)" => 65, "(농구)" => 66, 
      "(당구)" => 67, "(골프)" => 76, "(카톡)" => 68, "(꽃)" => 81, "(총)" => 82, 
      "(크리스마스)" => 80, "(콜)" => 77 ] 
  
    dict.each do |k, v|
      message.gsub!(k, "<span class = 'emoticon'><img src = '/assets/smallemoticons/emo#{'%02d' % v}.png'></span>")
    end

    message
  
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  layout 'frame'

  before_filter :set_chats, :only => [:index, :show, :new, :edit]

  private
  def set_chats
    if user_signed_in?
      @chats = current_user.chats
    else
      #redirect_to new_user_session_path
      @chats = User.first.chats
    end
  end


  public
  # GET /chats
  # GET /chats.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chats }
    end
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @chat = Chat.find(params[:id])
    @message = Message.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chat }
    end
  end

  # GET /chats/new
  # GET /chats/new.json
  def new
    @chat = Chat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chat }
    end
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.create_chat(params[:chat], current_user)

    respond_to do |format|
      if @chat
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render json: @chat, status: :created, location: @chat }
      else
        format.html { render action: "new" }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chats/1
  # PUT /chats/1.json
  def update
    @chat = Chat.find(params[:id])
    @chat.update_attributes(params[:chat])
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/chats_helper.rb
#coding: utf-8
module ChatsHelper
  require 'date'

  def html_maker(data)
    html = ''
    data.each do |m|
      case m.message_type
        when DATE, INVITATION, LEAVE
          html << info_maker(m)
        when MESSAGE
          html << "<div class = 'messageContainer' id = 'message_#{m.id}'>"
          html << edit_maker(m)
          if m.isMine
            html << "<div class = 'messageDiv isMine'>"
            html << message_maker(m) << "<div class = 'time'>#{m.message_time}</div>"
          else
            html << "<div class = 'messageDiv isNotMine'>"
            html << "<div class = 'profilePicContainer'><div class = 'profilePic'></div></div>"
            html << "<div class = 'rightPart'> <div class = 'name'> #{m.name} </div>"
            html << message_maker(m) << "<div class = 'time'> #{m.message_time} </div></div>"
          end
          html << "</div></div>"
      end
    end
    html
  end

  def edit_maker(m)
    "<div class='editDiv'>#{ button_to '삭제', chat_message_path(:chat_id => m.chat, :id => m), :remote => true, :method => :delete }</div>"

  end

  def message_maker(m)
    if m.content == TEXT
      "<div class = 'message textMessage'> #{m.message} </div>"
    elsif m.content == IMAGE
      "<div class = 'message imageMessage'> 
        <a class = 'messageImage' href='#{m.chat.get_file(m.message)}' target='_blank'> 
          <img src='/assets/uploaded/#{m.chat.get_file(m.message)}' /> 
        </a> 
      </div>"
    elsif m.content == AUDIO
      "<div class = 'message audioMessage'><a href = '#{m.message}'><img src = '/assets/voiceplay.png'></a></div>"
    elsif m.content == VIDEO
      "<div class = 'message videoMessage'><a href = '#{m.message}'><img src = '/assets/video.png'></a></div>"
    else
      "<div class = 'message unknownMessage'> #{m.message} </div>"
    end
  end

  def info_maker(m)
    "
      <div class = 'infoContainer' id = 'message_#{m.id}'>
        <div class = 'infoInnerContainer'>
          #{edit_maker(m)}
          <div class = 'infoLeftContainer'>
            <div class = 'infoLeftCol'></div>
            <div class = 'info'> #{m.message} </div>
          </div>
        </div>
        <div class = 'infoRightCol'></div>
      </div>
    "
  end


end

app/views/chats/_sidebar.mobile.erb
<h1>Listing chats</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chats.each do |chat| %>
  <tr>
    <td><%= chat.title %></td>
    <td><%= link_to 'Show', chat %></td>
    <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
    <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/edit.html.erb
<h1>대화 정보 편집</h1>



<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<h3>나의 대화목록</h3>
<div>
  통계 표시 / 없을 경우 <%= link_to '여기', new_chat_path %>를 눌러서 대화를 저장하거나 만들어주세요
</div>

<h3>인기 공유대화</h3>
<div>
  공유한 대화가 없습니다.
</div>

app/views/chats/index.mobile.erb
<% if user_signed_in? %>
	<li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
<% end %>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chats.each do |chat| %>
  <tr>
    <td><%= link_to chat.title , chat%></td>
    <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/chats/new.html.erb
<h1>대화 올리기</h1>

<h3>파일로 올리기</h3>
<div>
  <%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :chat_type, :value => UPLOADED %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :chatfile %><br />
    <%= f.file_field :chatfile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

<h3>메일로 올리기</h3>
<div>
  카카오톡의 내보내기 기능을 이용하여, <%= current_user.username %>@DOMAIN.COM으로 대화내역을 보내주세요! 자동으로 저장됩니다.
</div>

<h1>대화 만들기</h1>
<div>
  재미있는 이야기를 카카오톡 대화처럼 만들 수  있습니다!
</div>

<div>
  <%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :chat_type, :value => CREATED %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

</div>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <div class = 'chatTitle'>
    <span id = 'chatTitleText'><%= @chat.title %></span>
    <%= link_to_function 'Edit', 'toggleTitle()' %>
  </div>
  <div class = 'chatTitle transparent'>
    <%= form_for(@chat, :remote => true) do |c| %>
      <%= c.text_field :title %>
      <%= c.submit '수정' %>
    <% end %>
  </div>
</p>

<div class = 'chatScreen'>
	<div class = 'chat_list'>
    <%= html_maker(@chat.messages).html_safe %>
	</div>
</div>
<div>
  <% if @chat.chat_type == CREATED %>
    <%= form_for(@message, :url => chat_messages_path(@chat), :remote => true) do |f| %>
      <%= f.select :message_type, Message.option_for_messagetype %>

      <div class="messageFieldType1 messageField">
        <%= f.select :content, Message.option_for_content %>
        <%= f.select :isMine, Message.option_for_ismine %>
      </div>
      <div class="messageFieldType3 messageField">
        <%= f.text_field :name_by, :class => 'messageFieldName', :placeholder => '초대한 사람' %>
      </div>

      <%= f.text_field :name, :placeholder => '이름' %>
      <%= f.text_field :message, :placeholder => '내용' %>

      <%= f.submit '작성' %>
    <% end %>
  <% end %>
</div>

<ul class="sideMenu">
  <li><%= link_to_function '위', 'toTop();' %></li>
  <li><%= link_to_function '아래', 'toBottom();' %></li>
  <li><%= link_to_function '공유', "toggleShare('#{@chat.id}');" %></li>
  <li><%= link_to_function '편집', 'toggleEdit();' %></li> 
  <li><%= link_to '뒤로', chats_path %></li>
</ul>

app/views/chats/show.mobile.erb
<div class = "chatContainer">
  <div class = "chatScreen">
    <div class = "chat_list">

      <% if @chat.chatfile? %>
        <%= html_maker(@chat.messages).html_safe %>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/update.js.erb
$("#chatTitleText").html("<%= @chat.title %>");
toggleTitle();