config/routes.rb
Kakaoreview::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :main, :only => ['index']
  resources :quotes do
    resources :comments
    member do
      post :rate
    end
  end
  resources :chats do
    resources :parts
    resources :messages
  end
	resources :emails

  match 'help' => 'main#help'

  root :to => 'main#index'

end

app/views/layouts/_footer.html.erb
2013 <%= link_to 'Wafflestudio', 'http://www.wafflestudio.com' %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <%= link_to 'Kakao Review for 잉여=너', root_path, :class => "brand" %>
    <ul class="nav">
        <li><%= link_to '인기대화', quotes_path %></li>
        <li><%= link_to '대화만들기', new_chat_path %></li>
        <li><%= link_to '대화저장소', chats_path %></li>
        <li><%= link_to '도움말', help_path %></li>
    </ul>
    <ul class="nav">
      <% if user_signed_in? %>
        <li><%= link_to '로그아웃', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to '회원가입', new_user_registration_path %></li>
        <li><%= link_to '로그인', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kakaoreview</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <!-- Navigation bar -->
    <%= render :partial => 'layouts/header' %>
    <!-- Navigation bar end -->

    <div class="row-fluid">
      <div id="content_box" class="offset1 span10">
        <!-- Contents -->
        <%= yield %>
      </div>
    </div>
  </div>

  <%= render :partial => 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Kakaoreview</title>
  	<%= stylesheet_link_tag    "mobile", :media => "all" %>
  	<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<meta name="apple-mobile-web-app-capable" content="yes">
	</head>

	<body>
		<%= yield %>
	</body>

</html>

app/views/layouts/frame.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kakaoreview</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <!-- Navigation bar -->
    <%= render :partial => 'layouts/header' %>
    <!-- Navigation bar end -->

    <div class="row-fluid">
      <div class="span2">
        <!-- Sidebar contents -->
        <div class="well">
        <%= render :partial => 'sidebar' %>
        </div>
      </div>
      <div id="content_box" class="span10">
        <!-- Contents -->
        <%= yield %>
      </div>
    </div>
  </div>

  <%= render :partial => 'layouts/footer' %>
</body>
</html>

app/views/layouts/frame.mobile.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Kakaoreview</title>
  	<%= stylesheet_link_tag    "mobile", :media => "all" %>
  	<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<meta name="apple-mobile-web-app-capable" content="yes">
	</head>

	<body>
		<%= yield %>
	</body>

</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kakaoreview</title>
  <%= stylesheet_link_tag    "mobile", :media => "all" %>
  <%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
	<li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
	<% else %>
	<li><%= link_to 'Sign up', new_user_registration_path %></li>
	<li><%= link_to 'Login', new_user_session_path %></li>
	<% end %>
  <%= yield :sidebar %>
	<%= yield %>
</body>
</html>

app/views/layouts/part.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Kakaoreview</title>
  	<%= stylesheet_link_tag    "mobile", :media => "all" %>
  	<%#= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<meta name="apple-mobile-web-app-capable" content="yes">
	</head>

	<body>
		<%= yield %>
	</body>

</html>